kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-storage-pv
  labels:
      stack: lilly
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /db_storage
    server: 172.16.0.253
