---
common:
    registry_url: registry.walkure.net:5000
applications:
    - lilly-api
app_spec:
    - name: lilly-api
      image_name: lilly
      metadata:
            layer: api
            lang: python
      replicas: 2
      ports: [5000]
      resources:
          requests:
              cpu: 100m
              memory: 512Mi
      properties:
          env_name: default
          MESSAGE: Hello World!
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          MONGO_DBNAME: lilly
          MONGO_USERNAME: ''
          MONGO_PASSWORD: ''

